### ISSUE TITLE
duration metric is only available as histogram over the whole runtime of the exporter

### ISSUE THREAD

**Issue by frittentheke** [inovex/mqtt_blackbox_exporter#17]
Currently the probeDuration metric is only available as NewHistogramVec which is never reset during the runtime of the exporter and with no sliding window.
This results in strange values if there was even a brief period of long duration and makes the metric useless for triggering alerts.

Suggestions: 

* Add a simple scalar value containing just the last run

 * Use the histogram only on the last / a single run of the exporter towards the MQTT service. This allows to access the timing spread of message publication to subscription latency.

**Comment by hikhvar** [comment]
Using only the last N values etc does not help since each histogram bucket is and should be 
a counter. You can use the following PromQL Feature to calculate the probe duration in the last 5m: https://prometheus.io/docs/practices/histograms/#count-and-sum-of-observations

**Comment by hikhvar** [comment]
Can we close this issue?

**Comment by frittentheke** [comment]
I suppose.

**Comment by arnisoph** [comment]
Thanks!
