### ISSUE TITLE
shared prometheus alert rules for mqtt_blackbox_exporter

### ISSUE THREAD

**Issue by huydinhle** [inovex/mqtt_blackbox_exporter#33]
Anyone can share their alerts for the exporter ? I don't have much experience operating mqtt, and would love to steal some of the alerts people using

**Comment by hikhvar** [comment]
@frittentheke do you have some at hand?

**Comment by huydinhle** [comment]
@hikhvar  thank you for your reference

**Comment by arnisoph** [comment]
@huydinhle take a look at #35. Feel free to provide feedback in that issue. I'll close this one.
