### ISSUE TITLE
Failed to pull image + grafana dashboard

### ISSUE THREAD

**Issue by sgu-fai** [inovex/mqtt_blackbox_exporter#34]
Hello,

am I supposed to be able to use the image ?

> inovex/mqtt_blackbox_exporter

I am getting:
`Failed to pull image "inovex/mqtt_blackbox_exporter": rpc error: code = Unknown desc = Error response from daemon: manifest for inovex/mqtt_blackbox_exporter:latest not found`

Also I was wondering if you were about any grafana dashboard for mosquitto ? (I didn't find one on their website)

thank you

**Comment by arnisoph** [comment]
Please don't use tag "latest". We don't maintain that tag at all. (=> latest is not a version)

See https://cloud.docker.com/u/inovex/repository/docker/inovex/mqtt_blackbox_exporter/tags for available image tags.
We don't maintain any dashboards here yet. Feel free to contribute. :)
