### ISSUE TITLE
how to monitor SYS-Topics

### ISSUE THREAD

**Issue by alochym01** [inovex/mqtt_blackbox_exporter#37]
there is no documents for monitor SYS-Topics

https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics

please help

**Comment by hikhvar** [comment]
This exporter does not export metrics for the SYS topics. As the above documentation states, there is no standard for the SYS topics and their semantics. 

This exporter sends messages to the broker and reads them back. Thus the broker itself is a blackbox for the exporter. The exporter monitors only if the messages are delivered by the broker.

**Comment by alochym01** [comment]
thank you
