### ISSUE TITLE
Can't build for ARM?

### ISSUE THREAD

**Issue by zoide** [inovex/mqtt_blackbox_exporter#40]
Hi there,

I've just stumbled upon your code. Unfortunatly it does not build for ARM on Linux. Well, actually, it builds on ARM, but creates amd64 binaries.

Is there a reason for that? If the code can run on linux/arm I'd give it a try.

Cheers!

**Comment by hikhvar** [comment]
If you build on arm, a `make build/mqtt_blackbox_exporter` should build a ARM binary.

However, you are correct, the `make linux` target builds only amd64 binaries. I will add arm specific build targets to cross compile for ARM.

**Comment by arnisoph** [comment]
@zoide please try https://github.com/inovex/mqtt_blackbox_exporter/releases/tag/v0.5.0 :)

thanks to @hikhvar for proving the PR

**Comment by zoide** [comment]
Thanks all, it works!
