### ISSUE TITLE
I tested it and it can be used normally, but it is all useless data ：(

### ISSUE THREAD

**Issue by dudumao520** [inovex/mqtt_blackbox_exporter#53]
Hi,I tested it and it can be used normally, but it is all useless data,the value of temperature and humidity is not obtained
[http_content.zip](https://github.com/inovex/mqtt_blackbox_exporter/files/6820426/http_content.zip)
Please give me some suggestions, thank you very much！
I just want to get the temperature and humidity value, in the mqtt server, I can see the temperature and humidity value！
ThankYou!
@inovex-github

**Comment by dudumao520** [comment]
@hikhvar

**Comment by arnisoph** [comment]
I think you did not understood the use case of this project. The mqtt_blackbox_exporter is about monitoring MQTT servers/brokers, not exporting their topics.

Are you looking for https://github.com/hikhvar/mqtt2prometheus?

**Comment by dudumao520** [comment]
> I think you did not understood the use case of this project. The mqtt_blackbox_exporter is about monitoring MQTT servers/brokers, not exporting their topics.
> 
> Are you looking for https://github.com/hikhvar/mqtt2prometheus?

Thank you !
