### ISSUE TITLE
Docker image for v0.8.0?

### ISSUE THREAD

**Issue by bobeal** [inovex/mqtt_blackbox_exporter#54]
Hello,

I saw a new version has been released yesterday but it is not available on https://hub.docker.com/r/inovex/mqtt_blackbox_exporter. Is there a plan to publish it soon?

Thanks in advance for your feedback.

**Comment by hikhvar** [comment]
I have to look into it. I thought the release process was completly automated. It seems, it wasn't. I try to publish it there.

**Comment by hikhvar** [comment]
Pushed the image for v0.8.1 today.

Maybe as a preliminary warning, I will leave inovex end of march. Currently, I'm searching a new maintainer for this project. If not found, I will archive this repository to make clear, this tool is not maintained anymore.
